---
title: "GIS_PROJECT"
author: "Cailin Roberts"
output:
html_document:
self-contained: true
---

## install packages

```{r}
library(sf)
library(st)
library(tidyverse)
library(rinat)
library(GGally)
library(ggplot2)
library(rosm)
library(ggspatial)
library(prettymapr)
library(leaflet)
library(htmltools)
library(mapview)
library(leafpop)
library(wesanderson)
library(htmltools)
```

## Getting data from iNaturalist

```{r}
pc <- get_inat_obs(taxon_name = "Laminaria pallida", bounds = c(-35, 18, -33.5, 18.5), year = 2014, maxresults = 1000)

head(pc)
```

# Filter returned observations by a range of column attribute criteria

```{r}
pc <- pc %>% filter(positional_accuracy<46 & 
                latitude<0 &
                !is.na(latitude) &
                captive_cultivated == "false" & quality_grade == "research")

class(pc)
```

# Make the dataframe a spatial object of class = "sf"

```{r}
pc <- st_as_sf(pc, coords = c("longitude", "latitude"), crs = 4326)
```

## what class is it

```{r}
class(pc)
```

# Note the new "geometry" column

```{r}
names(pc)
```

## plot

```{r}
ggplot() + geom_sf(data=pc)
```

## Adding basemaps

```{r}
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=pc)
```

```{r}
leaflet() %>% addTiles(group = "Default") %>% addCircleMarkers(data = pc,
                   group = "Laminaria pallida", radius = 3, color = "green")   
```

## common sense checks

```{r}
mapview(pc, 
        popup = 
          popupTable(pc,
            zcol = c("user_login", "captive_cultivated", "url")))
```

## make live links

```{r}
lpc <- pc %>%
  mutate(click_url = paste("<b><a href='", url, "'>Link to iNat observation</a></b>"))

mapview(pc, 
        popup = 
          popupTable(lpc,
            zcol = c("user_login", "captive_cultivated", "click_url")))
```

```{r}
st_crs(pc)
```
